image: golang:1.24-bookworm

variables:
  APPLICATION_NAME: 'totp_code_generator'
  APPLICATION_PATH: '/go/src/github.com/'
  GO_SRC: "/go/src"
  CI_IMAGE: "golang:1.24-bookworm"
  TEST_COVERAGE: test.cover
  TEST_REPORT: report.json

stages:
    - Image
    - Quality
    - Linter

Unit:
    stage: Quality
    image: $CI_IMAGE
    script:
        - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - go install github.com/rakyll/gotest@latest
        - make test

Linter:
    stage: Quality
    image: $CI_IMAGE
    script:
        - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - go install github.com/rakyll/gotest@latest
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
        - make lint