name: Go CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up job container
        run: |
          docker pull leonamsimoes/totp_code_generator_001:latest
      - name: Test (in container)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace leonamsimoes/totp_code_generator_001:latest make test
      - name: Lint (in container)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace leonamsimoes/totp_code_generator_001:latest make lint
